### ISSUE TITLE
Which part code do the job of Peak Detector and Voice Activity Detector?

### ISSUE THREAD

**Issue by liuslevis** [jorgehatccrma/pyagc#1]
Really awesome and inspiring code.
In AGC of time-amplitude domain, there're Peak Detector, Voice Activity Detector and Gain Control modules.
My problem raises: in pyagc, which part code do the job of Peak Detector and Voice Activity Detector?

**Comment by jorgehatccrma** [comment]
This is just the Gain Control part. There's no peak detector or voice activity detector. As mentioned in the README, it is based on [this matlab implementation](http://labrosa.ee.columbia.edu/matlab/tf_agc/), so you should read that to understand what is implemented. In short, from that page:

 > This code implements automatic gain control for audio signals, which attempts to apply a smoothly-varying gain to an audio waveform in order to keep its energy close to some target level. This version also tries to balance the energy in individual frequency bands.
